language: clojure
#sudo: true
#services:
#  - elasticsearch

env:
  matrix:
    - ES_VERSION="2.3.1"
  global:
    - ES_URL="http://localhost:9200"
    - ES_CLUSTER_NAME=elasticsearch
    - ES_CLUSTER_HOST="127.0.0.1"

before_install:
  - "ulimit -u 4096"
  - "curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.1/elasticsearch-2.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.1.deb && sudo service elasticsearch start"
  - sleep 5
  - elasticsearch -d --default.path.conf=resources/config
  - sleep 15
  - elasticsearch -v 
  - "curl $ES_URL"

script: lein2 all test :ci
jdk:
  - oraclejdk8
