language: clojure
sudo: true
services:
  - elasticsearch
env:
  global:
    - ES_URL="http://127.0.0.1:9200"
    - ES_CLUSTER_NAME=elasticsearch
    - ES_CLUSTER_HOST="127.0.0.1"

before_install:
  - "ulimit -u 4096"
  - "sudo curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.1/elasticsearch-2.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.1.deb"
  - "sudo service elasticsearch restart"
  - "sudo service elasticsearch status"
  - "sudo cp -r resources/config /usr/share/elasticsearch/config"
  - "sudo elasticsearch -v"
  - "curl http://localhost:9200/"

script: lein2 all test :ci
jdk:
  - oraclejdk8
