jdk:
  - oraclejdk8
language: clojure
lein: lein
sudo: required
services:
  - docker

env:
  - ES_VERSION="2.3.1"
env.global:
  - ES_URL="http://127.0.0.1:9200"
  - ES_CLUSTER_HOST="127.0.0.1"

before_install:
  - docker pull elasticsearch:2.3.1

install:
  - docker run -d -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 --name="elastisch-test" -v "$PWD/resources/config/elasticsearch.yml":/usr/share/elasticsearch/config/elasticsearch.yml elasticsearch:2.3.1
  - lein deps

before_script:
  - sleep 15

script:
  - docker ps -a
  - docker logs elastisch-test
  - curl -vvvv http://127.0.0.1:9200/_stats
  - lein with-profile 1.8,dev test :rest

