language: clojure
lein: lein
sudo: required
services:
  - docker

env:
  - ES_VERSION="2.3.1"

before_install:
  - "ulimit -u 4096"
  - docker pull elasticsearch:2.3.1
  - docker run -d -p 9200:9200 -p 9300:9300 -v "$PWD/resources/config":/usr/share/elasticsearch/config elasticsearch:2.3.1
  - docker ps -a

script: lein all test
jdk:
  - oraclejdk8
