language: clojure
#sudo: true
services:
  - docker

env:
  matrix:
    - ES_VERSION="2.3.1"
  global:
    - ES_URL="http://localhost:9200"
    - ES_CLUSTER_NAME=elasticsearch
    - ES_CLUSTER_HOST="127.0.0.1"

before_install:
  - "ulimit -u 4096"
  - docker pull elasticsearch:2.3.1
  - docker run -d -p 9200:9200 -p 9300:9300 --name="elastisch-test" -v "$PWD/resources/config":/usr/share/elasticsearch/config elasticsearch:2.3.1 -Des.node.name="es-test" -Des.network.bind_host=0.0.0.0
  - docker ps -a
  - "curl $ES_URL"

script: lein2 all test :ci
jdk:
  - oraclejdk8
