language: clojure
lein: lein
sudo: required
services:
  - docker

addons:
  hosts:
    - localhost

env:
  - ES_VERSION="2.3.1"
env.global:
  - "HOST_IP=$(/sbin/ifconfig venet0:0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
  - ES_URL="http://localhost:9200"
  - ES_CLUSTER_HOST="localhost"

before_install:
  - docker pull elasticsearch:2.3.1

install:
  - docker run -d -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 -v "$PWD/resources/config":/usr/share/elasticsearch/config elasticsearch:2.3.1
  - lein deps

script:
  - docker ps -a
  - sleep 5
  - curl -vvvv http://localhost:9200/_stats
  - lein with-profile 1.8,dev test :rest

jdk:
  - oraclejdk8
