language: clojure
sudo: true
services:
  - elasticsearch
env:
  - ES_CLUSTER_NAME=elasticsearch
before_install:
  - "ulimit -u 4096"
  - "curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.1/elasticsearch-2.3.1.deb"
  - "sudo dpkg -i --force-confnew elasticsearch-2.3.1.deb"
  - "sudo service elasticsearch restart"
  - "sudo service elasticsearch status"

script: lein2 all test :ci
jdk:
  - oraclejdk8
