language: clojure
sudo: true
#deactive when travis stop using 1.4
#services:
#  - elasticsearch

env:
  global:
    - ES_URL="http://127.0.0.1:9200"
    - ES_CLUSTER_NAME=elasticsearch
    - ES_CLUSTER_HOST="127.0.0.1"

before_install:
  - "ulimit -u 4096"
  - "sudo curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.1/elasticsearch-2.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.1.deb"
  - "sudo service elasticsearch start"
  - "sudo service elasticsearch status"
  - "sudo cp -r resources/config /usr/share/elasticsearch/config"
  - "curl $ES_URL"

script: lein2 all test :ci
jdk:
  - oraclejdk8
